# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_actor', models.CharField(max_length=250)),
                ('film_title', models.CharField(max_length=250)),
                ('director_name', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
            ],
        ),
    ]
