# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_album_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.CharField(max_length=1000),
        ),
    ]
